#!/bin/sh

echo "Removing EXIF metadata"

if ! which exiv2 > /dev/null; then
    echo "Please install the exiv2 tool"
    exit 0
fi

find . -iname '*.png' -or -iname '*.jpg' | while read fname; do
	echo "Scrubbing '$fname'"
	orientation=$(exiv2 -P v -K Exif.Image.Orientation "$fname")
	exiv2 -d a "$fname"
	if [ -n "$orientation" ]; then
		exiv2 -M "set Exif.Image.Orientation Short $orientation" "$fname"
	fi
done
